### ISSUE TITLE
All tests fail under observability profile 

### ISSUE THREAD

**Issue by tstephen** [odrotbohm/spring-restbucks#116] opened 2022-11-21 18:06 UTC
Steps to reproduce:
1. Checkout  `main` at commit id `a16bcabdf93b71ba3c94123aac0685d502f5dcca`
2. Run `mvn clean -Pobservability package`

Expect:
- All tests to pass

Actual:
- All tests fail, example below. Looks like modulith needs an upgrade for Spring Boot 3 compatibility
```
-------------------------------------------------------------------------------
Test set: org.springsource.restbucks.order.OrdersIntegrationTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.465 s <<< FAILURE! - in org.springsource.restbucks.order.OrdersIntegrationTest
findsOrderByStatus  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext for [WebMergedContextConfiguration@23a3e942 testClass = org.springsource.restbucks.order.OrdersIntegrationTest, locations = [], classes = [org.springsource.restbucks.Restbucks], contextInitializerClasses = [], activeProfiles = [], propertySourceLocations = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true"], contextCustomizers = [org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7bf3a5d8, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@72ef8d15, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@6ea2bc93, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@9da1, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@420a85c4, org.springframework.boot.test.context.SpringBootTestAnnotation@efcfef81], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'springDataRestModuleTracingBeanPostProcessor' defined in class path resource [org/springframework/modulith/observability/autoconfigure/SpringDataRestModuleObservabilityAutoConfiguration.class]: Unsatisfied dependency expressed through method 'springDataRestModuleTracingBeanPostProcessor' parameter 0: No qualifying bean of type 'org.springframework.modulith.observability.ApplicationRuntime' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.modulith.observability.ApplicationRuntime' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

createsNewOrder  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext for [WebMergedContextConfiguration@23a3e942 testClass = org.springsource.restbucks.order.OrdersIntegrationTest, locations = [], classes = [org.springsource.restbucks.Restbucks], contextInitializerClasses = [], activeProfiles = [], propertySourceLocations = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true"], contextCustomizers = [org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7bf3a5d8, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@72ef8d15, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@6ea2bc93, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@9da1, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@420a85c4, org.springframework.boot.test.context.SpringBootTestAnnotation@efcfef81], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'springDataRestModuleTracingBeanPostProcessor' defined in class path resource [org/springframework/modulith/observability/autoconfigure/SpringDataRestModuleObservabilityAutoConfiguration.class]: Unsatisfied dependency expressed through method 'springDataRestModuleTracingBeanPostProcessor' parameter 0: No qualifying bean of type 'org.springframework.modulith.observability.ApplicationRuntime' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.modulith.observability.ApplicationRuntime' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

findsAllOrders  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext for [WebMergedContextConfiguration@23a3e942 testClass = org.springsource.restbucks.order.OrdersIntegrationTest, locations = [], classes = [org.springsource.restbucks.Restbucks], contextInitializerClasses = [], activeProfiles = [], propertySourceLocations = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true"], contextCustomizers = [org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7bf3a5d8, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@72ef8d15, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@6ea2bc93, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@9da1, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@420a85c4, org.springframework.boot.test.context.SpringBootTestAnnotation@efcfef81], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'springDataRestModuleTracingBeanPostProcessor' defined in class path resource [org/springframework/modulith/observability/autoconfigure/SpringDataRestModuleObservabilityAutoConfiguration.class]: Unsatisfied dependency expressed through method 'springDataRestModuleTracingBeanPostProcessor' parameter 0: No qualifying bean of type 'org.springframework.modulith.observability.ApplicationRuntime' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.modulith.observability.ApplicationRuntime' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

**Comment by odrotbohm** [comment] 2023-10-26 09:17
Likely caused by spring-projects/spring-modulith#315, which has been fixed in the latest 1.1 RC1. The profile is still referencing experimental artifacts. About to be fixed.

**Closed** 2023-10-26 09:17 UTC
